disabled_rules:
  - closure_parameter_position
  - file_length
  - function_body_length
  - function_parameter_count
  - identifier_name
  - todo
  - type_name
  - xctfail_message
  - large_tuple
excluded:
  - Carthage

