name: Release
on:
  push:
    tags:
      - '*'

jobs:
  release:
    runs-on: macos-latest
    steps:
      - name: IRC notification
        uses: Gottox/irc-message-action@v1
        continue-on-error: true
        with:
          channel: '#repla-development'
          nickname: bot-${{ github.run_id }}
          message: |-
            ${{ github.event.repository.name }} ${{ github.job }} started ${{ github.actor }} pushed ${{ github.event.ref }} ${{ github.event.compare }}
      - uses: actions/checkout@v2
      - run: make archive
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: StringPlusPath.framework.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: IRC notification
        uses: Gottox/irc-message-action@v1
        continue-on-error: true
        with:
          channel: '#repla-development'
          nickname: bot-${{ github.run_id }}
          message: |-
            ${{ github.event.repository.name }} ${{ github.job }} finished ${{ github.actor }} pushed ${{ github.event.ref }} ${{ github.event.compare }}
